import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "@/app/_navigation/header";
import { ThemeProviderWrapper } from "@/components/theme/theme-provider";
import { Toaster } from "@/components/ui/sonner";
import {Sidebar } from "@/app/_navigation/sidebar/components/sidebar"
import { NuqsAdapter } from "nuqs/adapters/next/app"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Tickets App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ThemeProviderWrapper>
          <Header />
          <div className="flex overflow-hidden border-collapse h-screen">
          <Sidebar />
          <main className="
          py-18 px-5 overflow-y-auto overflow-x-hidden min-h-screen flex-1 flex-col flex bg-secondary/20"
          >
           <NuqsAdapter>
          {children}
        </NuqsAdapter>
          </main>
          </div>
          <Toaster expand/> 
        </ThemeProviderWrapper>
      </body>
    </html>
  );
}
